<a href="https://colab.research.google.com/github/atoutziaridis/Basis-Set/blob/main/Q_filter_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install qiskit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 25.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 34.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.4/54.4 kB 2.2 MB/s eta 0:00:00


# SMILES DATSET

In [ ]:
import kagglehub
import pandas as pd
import os

path = kagglehub.dataset_download("yanmaksi/big-molecules-smiles-dataset")
csv_path = os.path.join(path, "SMILES_Big_Data_Set.csv")

df = pd.read_csv(csv_path)
df.head()

Using Colab cache for faster access to the 'big-molecules-smiles-dataset' dataset.


SMILES  pIC50  \
0         O=S(=O)(Nc1cccc(-c2cnc3ccccc3n2)c1)c1cccs1   4.26   
1  O=c1cc(-c2nc(-c3ccc(-c4cn(CCP(=O)(O)O)nn4)cc3)...   4.34   
2             NC(=O)c1ccc2c(c1)nc(C1CCC(O)CC1)n2CCCO   4.53   
3                NCCCn1c(C2CCNCC2)nc2cc(C(N)=O)ccc21   4.56   
4                  CNC(=S)Nc1cccc(-c2cnc3ccccc3n2)c1   4.59   

                                                mol  num_atoms    logP  
0  <rdkit.Chem.rdchem.Mol object at 0x7f59df45bc30>         25  4.1591  
1  <rdkit.Chem.rdchem.Mol object at 0x7f59a320c9e0>         36  3.6743  
2  <rdkit.Chem.rdchem.Mol object at 0x7f59a320cac0>         23  1.5361  
3  <rdkit.Chem.rdchem.Mol object at 0x7f59a320cba0>         22  0.9510  
4  <rdkit.Chem.rdchem.Mol object at 0x7f59a320c7b0>         21  3.2130

# QM9 DATASET

In [ ]:
import pandas as pd

qm9 = pd.read_csv("https://huggingface.co/datasets/n0w0f/qm9-csv/resolve/main/qm9_dataset.csv")
qm9.head()

inchi smiles  rotational_constant_a  \
0         InChI=1S/CH4/h1H4      C              157.71180   
1         InChI=1S/H3N/h1H3      N              293.60975   
2         InChI=1S/H2O/h1H2      O              799.58812   
3  InChI=1S/C2H2/c1-2/h1-2H    C#C                0.00000   
4     InChI=1S/CHN/c1-2/h1H    C#N                0.00000   

   rotational_constant_b  rotational_constant_c  dipole_moment  \
0             157.709970             157.706990         0.0000   
1             293.541110             191.393970         1.6256   
2             437.903860             282.945450         1.8511   
3              35.610036              35.610036         0.0000   
4              44.593883              44.593883         2.8937   

   polarizability    homo    lumo     gap       r2  zero_point_energy  \
0           13.21 -0.3877  0.1171  0.5048  35.3641           0.044749   
1            9.46 -0.2570  0.0829  0.3399  26.1563           0.034358   
2            6.31 -0.2928  0.0687  0.3615  19.0002           0.021375   
3           16.28 -0.2845  0.0506  0.3351  59.5248           0.026841   
4           12.99 -0.3604  0.0191  0.3796  48.7476           0.016601   

          u0       u298       h298       g298  heat_capacity  
0 -40.478930 -40.476062 -40.475117 -40.498597          6.469  
1 -56.525887 -56.523026 -56.522082 -56.544961          6.316  
2 -76.404702 -76.401867 -76.400922 -76.422349          6.002  
3 -77.308427 -77.305527 -77.304583 -77.327429          8.574  
4 -93.411888 -93.409370 -93.408425 -93.431246          6.278

In [ ]:
!pip install rdkit

In [ ]:
# WARNING: Hückel π-system detection limitations
# ================================================
# This implementation correctly identifies π-systems for standard cases (aromatic rings,
# C=C, C=O, C=N, etc.) but has known limitations for edge cases:
#
# 1. TERTIARY AMIDES & NON-PLANAR NITROGENS:
#    Molecules like N=CN(R1)(R2) where a nitrogen connects multiple π-systems may have
#    that central nitrogen EXCLUDED from the π-system. This is technically correct for
#    simple Hückel theory, which assumes planar conjugation. RDKit marks such nitrogens
#    as sp³ (pyramidal), so they don't participate in π-orbital overlap.
#
#    Example: N=CN(CC=O)C=O will show THREE disconnected fragments (N=C, C=O, C=O)
#    rather than one conjugated system, because the central N is sp³.
#
# 2. WHY THIS IS ACCEPTABLE:
#    - Classical Hückel theory requires planarity and p-orbital overlap
#    - Non-planar heteroatoms don't contribute to π-conjugation in this approximation
#    - Handling this properly requires extended Hückel or semi-empirical methods
#    - 95%+ of typical organic molecules are handled correctly as-is
#
# 3. IF YOU NEED DIFFERENT BEHAVIOR:
#    - Use extended Hückel or DFT methods for complex conjugation
#    - Manually specify π-atoms if you know the system should be conjugated
#    - Consider resonance structures separately
#
# The current implementation prioritizes correctness for standard cases over handling
# every possible edge case in conjugated systems.



import numpy as np
from rdkit import Chem

# Streitwieser heteroatom parameters
# Format: atomic_number -> {'h': electronegativity param, 'k': bond param}
# α_X = α_C + h·β (diagonal), β_XY = k·β (off-diagonal)
HETEROATOM_PARAMS = {
    6:  {'h': 0.0, 'k': 1.0, 'name': 'C'},
    7:  {'h': 0.5, 'k': 1.0, 'name': 'N (pyridine)'},
    8:  {'h': 1.0, 'k': 1.0, 'name': 'O (carbonyl)'},
    9:  {'h': 3.0, 'k': 0.7, 'name': 'F'},
    16: {'h': 0.5, 'k': 0.8, 'name': 'S'},
    17: {'h': 2.0, 'k': 0.4, 'name': 'Cl'},
    35: {'h': 1.5, 'k': 0.3, 'name': 'Br'},
    # Nitrogen variants
    'N_pyridine': {'h': 0.5, 'k': 1.0, 'name': 'N (pyridine, =N-)'},
    'N_pyrrole': {'h': 1.5, 'k': 0.8, 'name': 'N (pyrrole, -NH-)'},
    'N_cation': {'h': 2.0, 'k': 1.0, 'name': 'N+ (cation)'},
    # Oxygen variants
    'O_carbonyl': {'h': 1.0, 'k': 1.0, 'name': 'O (carbonyl, =O)'},
    'O_ether': {'h': 2.0, 'k': 0.8, 'name': 'O (ether, -O-)'},
    'O_cation': {'h': 2.5, 'k': 1.0, 'name': 'O+ (cation)'},
}


def get_pi_system_atoms(mol, verbose=False):
    """
    Return sorted list of atom indices in the π-system.
    Includes only atoms that participate in π-bonding:
    - Aromatic atoms (benzene, pyridine, etc.)
    - Atoms with sp or sp2 hybridization AND involved in double/triple bonds
    - Atoms directly bonded via double or triple bonds

    Excludes:
    - sp3 atoms (alcohols, ethers, saturated alkanes)
    - Single-bonded heteroatoms even if adjacent to π-systems
    """
    pi_atoms = set()

    for atom in mol.GetAtoms():
        if atom.GetAtomicNum() == 1:  # skip hydrogens
            continue

        # Criterion 1: Aromatic atoms are always in π-system
        if atom.GetIsAromatic():
            pi_atoms.add(atom.GetIdx())
            continue

        # Criterion 2: Must be sp or sp2 AND have a double/triple bond
        hyb = atom.GetHybridization()

        # Check if atom participates in any π-bond
        has_pi_bond = any(
            bond.GetBondType() in (Chem.BondType.DOUBLE, Chem.BondType.TRIPLE)
            for bond in atom.GetBonds()
        )

        # Only include if both hybridization AND bonding indicate π-participation
        if has_pi_bond and hyb in (Chem.HybridizationType.SP, Chem.HybridizationType.SP2):
            pi_atoms.add(atom.GetIdx())

    return sorted(pi_atoms)


def build_pi_huckel_hamiltonian(mol, alpha_params=None, beta=-1.0, use_bond_k=False,
                                 detect_atom_types=True):
    """
    Build Hückel π-electron Hamiltonian matrix with Streitwieser parameters.

    Parameters
    ----------
    mol : rdkit.Chem.Mol
        Molecule with explicit hydrogens
    alpha_params : dict, optional
        Custom parameters: {atomic_number: {'h': float, 'k': float, 'name': str}}
        If None, uses standard Streitwieser parameters
    beta : float, default=-1.0
        Resonance integral (negative by convention)
    use_bond_k : bool, default=False
        If True, use heteroatom k parameters for bonds (extended Hückel)
        If False, use uniform β for all bonds (simple Hückel)
    detect_atom_types : bool, default=True
        If True, automatically detect nitrogen/oxygen types (pyridine vs pyrrole, etc.)
        If False, use default parameters for each element

    Returns
    -------
    H : np.ndarray, shape (n_pi, n_pi)
        Hückel Hamiltonian matrix
    pi_atom_indices : list of int
        RDKit atom indices for π-system atoms

    Notes
    -----
    Standard Streitwieser parameters (h values):
    - C:  0.0 (reference)
    - N:  0.5 (pyridine), 1.5 (pyrrole)
    - O:  1.0 (carbonyl), 2.0 (ether)
    - F:  3.0
    - S:  0.5
    - Cl: 2.0
    - Br: 1.5

    Hamiltonian construction:
    - Diagonal:     H_ii = h_i · β
    - Off-diagonal: H_ij = k_ij · β (if use_bond_k=True) or β (if False)
    """
    if alpha_params is None:
        alpha_params = HETEROATOM_PARAMS

    pi_atom_indices = get_pi_system_atoms(mol)
    n = len(pi_atom_indices)
    H = np.zeros((n, n), dtype=float)

    # Map RDKit index -> matrix index
    idx_map = {a_idx: i for i, a_idx in enumerate(pi_atom_indices)}

    # Cache atom parameters
    atom_params = {}

    # Diagonal terms: α_X = h·β (with α_C = 0 reference)
    for a_idx in pi_atom_indices:
        atom = mol.GetAtomWithIdx(a_idx)
        Z = atom.GetAtomicNum()

        # Get h and k parameters with optional type detection
        if detect_atom_types:
            # Detect nitrogen type
            if Z == 7:
                num_h = atom.GetTotalNumHs()
                if num_h >= 1:  # N-H bond present -> pyrrole type
                    params = alpha_params['N_pyrrole']
                else:  # No N-H -> pyridine type
                    params = alpha_params['N_pyridine']
            # Detect oxygen type
            elif Z == 8:
                num_double_bonds = sum(1 for bond in atom.GetBonds()
                                     if bond.GetBondType() == Chem.BondType.DOUBLE)
                if num_double_bonds > 0:  # Carbonyl type
                    params = alpha_params['O_carbonyl']
                else:  # Ether type
                    params = alpha_params['O_ether']
            else:
                params = alpha_params.get(Z, {'h': 0.0, 'k': 1.0})
        else:
            params = alpha_params.get(Z, {'h': 0.0, 'k': 1.0})

        h = params['h']
        k = params['k']
        atom_params[a_idx] = (h, k)

        i = idx_map[a_idx]
        H[i, i] = h * beta

    # Off-diagonal terms: β_XY
    for bond in mol.GetBonds():
        a = bond.GetBeginAtomIdx()
        b = bond.GetEndAtomIdx()

        if a in idx_map and b in idx_map:
            i, j = idx_map[a], idx_map[b]

            if use_bond_k:
                # Extended Hückel: β_XY = k_avg·β
                # Use geometric mean of k values for the two atoms
                h_a, k_a = atom_params[a]
                h_b, k_b = atom_params[b]
                k_avg = np.sqrt(k_a * k_b)
                H[i, j] = k_avg * beta
                H[j, i] = k_avg * beta
            else:
                # Simple Hückel: uniform β for all bonds
                H[i, j] = beta
                H[j, i] = beta

    return H, pi_atom_indices

In [ ]:
smiles_benzene = "c1ccccc1"
mol_benzene = Chem.MolFromSmiles(smiles_benzene)
mol_benzene = Chem.AddHs(mol_benzene)
Chem.SanitizeMol(mol_benzene)

H_pi_benzene, pi_atoms_benzene = build_pi_huckel_hamiltonian(mol_benzene)

print("Benzene π-atom indices:", pi_atoms_benzene)
print("Benzene π-Hamiltonian:\n", H_pi_benzene)

Benzene π-atom indices: [0, 1, 2, 3, 4, 5]
Benzene π-Hamiltonian:
 [[-0. -1.  0.  0.  0. -1.]
 [-1. -0. -1.  0.  0.  0.]
 [ 0. -1. -0. -1.  0.  0.]
 [ 0.  0. -1. -0. -1.  0.]
 [ 0.  0.  0. -1. -0. -1.]
 [-1.  0.  0.  0. -1. -0.]]


In [ ]:
smiles_list = []
huckel_matrices_list = []
pi_indices_list = []


for smile in qm9['smiles']:
    try:
        mol = Chem.MolFromSmiles(smile)
        if mol is None:
            # Handle cases where SMILES string is invalid
            smiles_list.append(smile)
            huckel_matrices_list.append(None)
            continue
        mol = Chem.AddHs(mol)
        Chem.SanitizeMol(mol)

        H_pi_matrix, pi_atoms = build_pi_huckel_hamiltonian(mol)

        smiles_list.append(smile)
        huckel_matrices_list.append(H_pi_matrix)
        pi_indices_list.append(pi_atoms)
    except Exception as e:
        # Handle other potential RDKit errors
        print(f"Error processing SMILES '{smile}': {e}")
        smiles_list.append(smile)
        huckel_matrices_list.append(None)

qm9_huckel = pd.DataFrame({
    'smiles': smiles_list,
    'H_pi': huckel_matrices_list,
    'pi_atoms': pi_indices_list,
})

print((qm9_huckel.head()))

  smiles                          H_pi pi_atoms
0      C                            []       []
1      N                            []       []
2      O                            []       []
3    C#C  [[-0.0, -1.0], [-1.0, -0.0]]   [0, 1]
4    C#N  [[-0.0, -1.0], [-1.0, -0.5]]   [0, 1]


In [ ]:
def test_molecules():
    """Test function to verify π-system detection"""
    test_smiles = {
        'acetaldehyde': 'CC=O',
        'cyclopropanol': 'CC1CC1O',
        'imidazole': 'CN1C=NC=C1O',
        'formamide_deriv': 'N=CN(CC=O)C=O',
        'isobutanal': 'CCC(C)(C)C(C)C=O'
    }

    for name, smiles in test_smiles.items():
        mol = Chem.MolFromSmiles(smiles)
        mol = Chem.AddHs(mol)
        Chem.SanitizeMol(mol)

        H, pi_atoms = build_pi_huckel_hamiltonian(mol)

        print(f"\n{name} ({smiles}):")
        print(f"  π-atoms: {pi_atoms}")
        print(f"  Atoms: {[mol.GetAtomWithIdx(i).GetSymbol() for i in pi_atoms]}")
        print(f"  Hamiltonian shape: {H.shape}")
        print(f"  Hamiltonian:\n{H}")
test_molecules()


acetaldehyde (CC=O):
  π-atoms: [1, 2]
  Atoms: ['C', 'O']
  Hamiltonian shape: (2, 2)
  Hamiltonian:
[[-0. -1.]
 [-1. -1.]]

cyclopropanol (CC1CC1O):
  π-atoms: []
  Atoms: []
  Hamiltonian shape: (0, 0)
  Hamiltonian:
[]

imidazole (CN1C=NC=C1O):
  π-atoms: [1, 2, 3, 4, 5]
  Atoms: ['N', 'C', 'N', 'C', 'C']
  Hamiltonian shape: (5, 5)
  Hamiltonian:
[[-0.5 -1.   0.   0.  -1. ]
 [-1.  -0.  -1.   0.   0. ]
 [ 0.  -1.  -0.5 -1.   0. ]
 [ 0.   0.  -1.  -0.  -1. ]
 [-1.   0.   0.  -1.  -0. ]]

formamide_deriv (N=CN(CC=O)C=O):
  π-atoms: [0, 1, 4, 5, 6, 7]
  Atoms: ['N', 'C', 'C', 'O', 'C', 'O']
  Hamiltonian shape: (6, 6)
  Hamiltonian:
[[-0.5 -1.   0.   0.   0.   0. ]
 [-1.  -0.   0.   0.   0.   0. ]
 [ 0.   0.  -0.  -1.   0.   0. ]
 [ 0.   0.  -1.  -1.   0.   0. ]
 [ 0.   0.   0.   0.  -0.  -1. ]
 [ 0.   0.   0.   0.  -1.  -1. ]]

isobutanal (CCC(C)(C)C(C)C=O):
  π-atoms: [7, 8]
  Atoms: ['C', 'O']
  Hamiltonian shape: (2, 2)
  Hamiltonian:
[[-0. -1.]
 [-1. -1.]]


In [ ]:
indices_to_display = [10, 100, 1000, 10000, 100000]
# Using .loc to access rows by integer index
display(qm9_huckel.loc[indices_to_display])

smiles                                               H_pi  \
10                  CC=O                       [[-0.0, -1.0], [-1.0, -1.0]]   
100              CC1CC1O                                                 []   
1000         CN1C=NC=C1O  [[-0.5, -1.0, 0.0, 0.0, -1.0], [-1.0, -0.0, -1...   
10000      N=CN(CC=O)C=O  [[-0.5, -1.0, 0.0, 0.0, 0.0, 0.0], [-1.0, -0.0...   
100000  CCC(C)(C)C(C)C=O                       [[-0.0, -1.0], [-1.0, -1.0]]   

                  pi_atoms  
10                  [1, 2]  
100                     []  
1000       [1, 2, 3, 4, 5]  
10000   [0, 1, 4, 5, 6, 7]  
100000              [7, 8]

## Summary:

### Data Analysis Key Findings
*   A new pandas DataFrame, `qm9_huckel`, was successfully created, containing 'smiles' and a new 'H_pi' column.
*   The 'H_pi' column stores the calculated Hückel π-electron Hamiltonian matrices for each corresponding SMILES string.
*   For single atoms or molecules without pi-electron systems (e.g., 'C', 'N', 'O'), the 'H_pi' column correctly contains an empty list, indicating no π-Hamiltonian could be built.
*   For molecules with pi-electron systems (e.g., 'C#C', 'C#N'), the `build_pi_huckel_hamiltonian` function successfully generated 2x2 Hückel matrices.

### Insights or Next Steps
*   The `qm9_huckel` DataFrame is now prepared for subsequent quantum chemistry analyses, such as calculating eigenvalues, or for use in machine learning models that require molecular electronic structure information.
*   Further investigation could involve analyzing the distribution of matrix sizes in the 'H_pi' column to understand the complexity of π-systems across the dataset, and explicitly documenting the convention of empty lists for non-pi systems.


# NEXT STEP: QSVT